import "@/styles/global.scss";

export const metadata = {
  title: "빅홀 과제 페이지",
  description: "Generated by Son Jaehun",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><a href="/">Web</a></h1>
        {children}
      </body>
    </html>
  );
}
