import "@/styles/main.scss"; 

export const metadata = {
  title: "손재훈 과제 페이지",
  description: "Generated by Son Jaehun",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}
